// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteAssets(arg1) {
  return window['go']['main']['App']['DeleteAssets'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportCSV'](arg1, arg2);
}

export function ListAssets(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAssets'](arg1, arg2, arg3);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ManualAddAssets(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManualAddAssets'](arg1, arg2, arg3);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}
