// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {db} from '../models';
import {scanner} from '../models';

export function BatchAddTag(arg1:Array<number>,arg2:string):Promise<void>;

export function BatchRemoveTag(arg1:Array<number>,arg2:string):Promise<void>;

export function CancelJob(arg1:string):Promise<void>;

export function CountAssetStats(arg1:number):Promise<Record<string, number>>;

export function CreateProject(arg1:string):Promise<number>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteAssets(arg1:Array<number>):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetSetting(arg1:string):Promise<string>;

export function ImportCSV(arg1:number,arg2:string):Promise<Record<string, any>>;

export function ListAssets(arg1:number,arg2:string,arg3:string):Promise<Array<model.Asset>>;

export function ListAssetsPage(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<db.AssetPageResult>;

export function ListProjects(arg1:string):Promise<Array<model.Project>>;

export function ManualAddAssets(arg1:number,arg2:Array<string>,arg3:string):Promise<model.ImportResult>;

export function PauseJob(arg1:string):Promise<void>;

export function RenameProject(arg1:number,arg2:string):Promise<void>;

export function ResumeJob(arg1:string):Promise<void>;

export function RunDns(arg1:number,arg2:scanner.DnsConfig):Promise<string>;

export function RunHttpx(arg1:number,arg2:scanner.HttpxConfig):Promise<string>;

export function RunNaabu(arg1:number,arg2:scanner.NaabuConfig):Promise<string>;

export function RunRustscan(arg1:number,arg2:scanner.RustscanConfig):Promise<string>;

export function RunSubdomain(arg1:number,arg2:scanner.SubdomainConfig):Promise<string>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateTags(arg1:number,arg2:Array<string>):Promise<void>;
