// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchAddTag(arg1, arg2) {
  return window['go']['main']['App']['BatchAddTag'](arg1, arg2);
}

export function BatchRemoveTag(arg1, arg2) {
  return window['go']['main']['App']['BatchRemoveTag'](arg1, arg2);
}

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function CountAssetStats(arg1) {
  return window['go']['main']['App']['CountAssetStats'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteAssets(arg1) {
  return window['go']['main']['App']['DeleteAssets'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function ImportCSV(arg1, arg2) {
  return window['go']['main']['App']['ImportCSV'](arg1, arg2);
}

export function ListAssets(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAssets'](arg1, arg2, arg3);
}

export function ListAssetsPage(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ListAssetsPage'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ManualAddAssets(arg1, arg2, arg3) {
  return window['go']['main']['App']['ManualAddAssets'](arg1, arg2, arg3);
}

export function PauseJob(arg1) {
  return window['go']['main']['App']['PauseJob'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function ResumeJob(arg1) {
  return window['go']['main']['App']['ResumeJob'](arg1);
}

export function RunDns(arg1, arg2) {
  return window['go']['main']['App']['RunDns'](arg1, arg2);
}

export function RunHttpx(arg1, arg2) {
  return window['go']['main']['App']['RunHttpx'](arg1, arg2);
}

export function RunNaabu(arg1, arg2) {
  return window['go']['main']['App']['RunNaabu'](arg1, arg2);
}

export function RunRustscan(arg1, arg2) {
  return window['go']['main']['App']['RunRustscan'](arg1, arg2);
}

export function RunSubdomain(arg1, arg2) {
  return window['go']['main']['App']['RunSubdomain'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function UpdateTags(arg1, arg2) {
  return window['go']['main']['App']['UpdateTags'](arg1, arg2);
}
