// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function CreateProject(arg1:string):Promise<number>;

export function DeleteAsset(arg1:number):Promise<void>;

export function DeleteAssets(arg1:Array<number>):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetSetting(arg1:string):Promise<string>;

export function ImportCSV(arg1:number,arg2:string):Promise<Record<string, any>>;

export function ListAssets(arg1:number,arg2:string,arg3:string):Promise<Array<model.Asset>>;

export function ListProjects(arg1:string):Promise<Array<model.Project>>;

export function ManualAddAssets(arg1:number,arg2:Array<string>,arg3:string):Promise<model.ImportResult>;

export function RenameProject(arg1:number,arg2:string):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
